config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  get '/users/:id' => 'users#show', as: :user
  get 'sign_up'=> 'users#new', as: :signup
  post '/users' => 'users#create', as: :users
  get '/admin' => 'posts#new', as: :new_post
  post 'posts' => 'posts#create', as: :posts
  get 'sign_in' => 'session#new', as: :sign_in
  get 'tags/tags' => 'tags#show', as: :tag
  delete 'sign_out' => 'session#delete', as: :sign_out
  post 'auth' => 'session#create', as: :auth
  delete 'posts/:id' => 'posts#delete', as: :delete_post

end

app/models/post.rb
class Post < ActiveRecord::Base

  mount_uploader :photo, PhotoUploader

  validates :title,
  presence: true
  acts_as_taggable

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by(id: session[:user_id])
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action do
    @posts = Post.all
                  .order("created_at desc")
                  .page(params[:page])

    if @current_user.nil?
      redirect_to sign_in_path
    end

  end

  def index
    @post = Post.new
  end


  def new
    @post = Post.new
  end


  def create
    @post = Post.new params.require(:post).permit(:title, :photo, :tag_list)
    @post.user = @current_user
      if @post.save
        redirect_to root_path
      else
        render :new
      end
  end

  def delete
    @post = Post.find params[:id]
    @post.destroy
    redirect_to root_path
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    username = params[:username]
    password = params[:password]

    user = User.find_by username: username
      if (user) && (user.authenticate password)
        session[:user_id] = user.id
        redirect_to root_path
      else
        flash.now[:alert] = "TRY AGAIN"
        render :new
      end
  end

  def delete
    session.delete :user_id
    redirect_to root_path, notice: "Hasta lluego 😎"
  end




end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show

    tag_name = params[:tag]
    @posts = Post.tagged_with(tag_name)
                 .order("created_at desc")
                 .page
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
  @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit(:username, :password, :password_confirmation)
    if @user.save
    session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    if @current_user.nil?
      redirect_to sign_in_path
    else
      @user = User.find(params[:id])
    end

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HwDay27</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <nav class="navbar">
    <div class="nav">
      <% if @current_user.present?%>
        <%= link_to "Home", root_path%>
        <%= link_to "Sign Out", sign_out_path, method: :delete %>
        <%end %>

    </div>
  </nav>

  <% if @current_user.present? %>
    <h4> Hello <%= @current_user.username %></h4>
      <% end %>
      <% if alert %>
        <div class="alert alert-success" role="alert"> <%= alert %> </div>
      <% end %>


<%= yield %>

</body>

</html>

app/views/posts/_form.html.erb
<div class="form">

<% @posts.in_groups_of(3, false) do |posts| %>
  <div class="row">
    <% posts.each do |post| %>
      <div class="col-md-4">
        <div>
          <br>
            <%= image_tag post.photo.url(:large), class: "media-object img-rounded img-responsive" %>

            <% if post.user_id == @current_user.id %>
              <%= link_to 'Delete', delete_post_path(id: post.id), class: " pull-right btn btn-primary btn-sm", method: 'delete', data: {confirm: 'Are you sure!?!?!'}%>
            <% end %>

              <em>Posted <%= distance_of_time_in_words_to_now post.created_at %> ago</em> <br>
              <strong>Posted by: <%= post.user.username %> </strong>

        </div>
        <h4 class="tag">#<%= post.tag_list.map{|tag| link_to tag, tag_path(tag: tag)}.join("  #").html_safe %> </h4>
      </div>


    <% end %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="container">

  <div class="jumbotron">
    <h1> Not all who wander are lost </h1>
    <h5> Upload a memory </h5>
    <%= link_to "UPLOAD", new_post_path, class: "btn btn-primary btn-lg"%>
  </div>

  <h4> <%= pluralize @posts.total_count, "Picture" %> </h4>
    <%= render partial: "posts/form" %>
    <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <%= simple_form_for @post do |f| %>
    <%= f.input :title %>
    <%= f.input :photo %>
    <%= f.input :tag_list, label: "Tags", hint: "Tags should be separated by commas" %>
    <%= f.submit 'Upload', class: 'btn btn-primary' %>
    <%end%>
</div>

app/views/session/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="jumbotron">
  <h1> Welcome </h1>
    <p> Go ahead and sign in </p>
    <%=form_tag auth_path, method: :post do %>
      <div>
        <%= label_tag :username   %>
        <%= text_field_tag :username, "", class: "form-control"%>
      <br>
      </div>

      <div>
        <%= label_tag :password %>
        <%= password_field_tag :password, "", class: "form-control" %>
      <br>
      </div>

      <div>
        <%= submit_tag "Sign In", class: "btn btn-primary btn-lg"%>
        <br>
        <br>
        <p>Still don't have an account? Whatcha waitin' for? <%=link_to 'Sign up now', signup_path %> </p>
      </div>

    <% end %>
  </div>
</div>

app/views/tags/show.html.erb
<div class="container" >

  <%= render partial: "posts/form" %>
</div>

app/views/users/new.html.erb
<div class="container" >
<div class=" center jumbotron">

  <h1>Go on and sign up</h1>
    <h4> All the cool kids are doing it. </h4>

</div>

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= simple_form_for @user do |f| %>
          <%= f.input :username%>
          <%= f.input :password %>
          <strong> *Confirm Password </strong>
          <%= f.input :password_confirmation, label: false %>
          <%= f.button :submit %>
          <%end%>
          <br>
          <br>
      </div>
    </div>

</div>